id: P84635708
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN9311
  title: དཔལ་དགེ་ལྡན་པའི་ལམ་རིམ་དང་སྙན་བརྒྱུད་ཀྱི་ཆོས་སྐོར།
  volumes:
    f7e231f786b94349aa68023f3c94630a:
      image_group_id: I3CN9313
      title: ''
      base_file: v001.txt
  author: ''
